### ISSUE TITLE
Syntax highlight: the font-size gets bigger on mobile browser view if we write long code on a line.

### ISSUE THREAD

**Issue by alfieqashwa** [narative/gatsby-theme-novela#138]
**version 0.6.5**
**Local data source**

**Describe the bug**
on syntax-highlight, the font-size gets bigger on mobile browser view when write long characters.

**To Reproduce**
Try add this:

```jsx
var sOne, sTwo = "JavaScript syntax highlighting", "Long string to check the view from the mobile browser";
alert(s)
```
and compare with
```jsx
var sOne = "JavaScript syntax highlighting";
alert(s)
```
then the first one is bigger than the second one.

**Expected behavior**
it should not gets bigger. In mobile browser view (Chrome, Firefox, Safari) I see kentcdodds.com the behavior that i explained is not happen (also the line-highlight ends perfectly along the line).

**Screenshots**
![64074519-7f296e00-ccd6-11e9-8478-0f93463e5bff](https://user-images.githubusercontent.com/15263927/65052064-3212f080-d994-11e9-855a-90346213d1ee.PNG)

the screenshot i took from the mobile browser view when was opening https://sebastienlorber.com/handling-api-request-race-conditions-in-react

**Browser**
 - Browser chrome, mozilla firefox, iOS safari

**Additional context**

i've been looking to https://github.com/kentcdodds/kentcdodds.com/blob/master/src/components/mdx/code.js and https://github.com/kentcdodds/kentcdodds.com/blob/master/src/components/layout.js also that behavior is mention in https://www.gatsbyjs.org/packages/gatsby-remark-prismjs/#optional-add-line-highlighting-styles trying to find solution myself so i can make PR to helps novela-theme. But until now I don't find it. Sorry.

**Comment by brotzky** [comment]
Interesting! Thanks for the report, will take a look.

**Comment by alfieqashwa** [comment]
@brotzky Sir, I shadowing components/MDX like this 
https://github.com/alfieqashwa/alfieqashwa.me/commit/983e113f9eb6e62f3ceeb6ed82d8e79dfcb1559c

The code on mobile browser view is better, I guess. Probably you find more better.

**Comment by Haja-andri** [comment]
Hi Dennis, 

I have fixed this locally a while ago. I'd like to submit a PR but I am having trouble committing and push my fixe. 
Following are the steps I have followed

- Forked the repo
- Cloned locally
- Created a branch
- Fixed and tested locally 
- git add .
- git commit -m "Fixe for mobile view when code overflow the box size and font size get too big"

But the commit here give me back the error, 
<img width="903" alt="Screenshot 2019-10-11 at 17 41 11" src="https://user-images.githubusercontent.com/49898644/66665231-69508680-ec4e-11e9-9432-ec8f4b1d3b67.png">

I suspect its because I have edited the @narativ directory directly? I can also shadow and make the fixe from www, but how would the them get the fixe if once merged?

Could you give me some indication as for how to proceed to finalise the PR? 

By the way, this is a really awesome Template, you guys rocks :)

Cheers

**Comment by brotzky** [comment]
Follow the commit message template found in the "Get help: LINK" guide in the error message!

Check the most recent commits to this repo to see some examples of commit messages as well:
https://github.com/narative/gatsby-theme-novela/commits/master

I think after that you should be fine to commit. Really appreciate the fix :)!

**Comment by Haja-andri** [comment]
Thanks for getting back to me on your weekend Dennis! I managed to create the PR, I hope you will find it helpful. This is in fact my first ever PR to contribute to an external repo (started learning to code 4 months ago, that explains my questions above :). I am personally using this theme for several reasons. Firstly because it is abvioiusly  just absolutely beautiful. And Secondly, because I wanted to learn to use Gatsby/GraphQL. And there is no better way to learn than using it. You can checkout my blog [here](andriam.com). I still have few PRs that I'd like to submit (some customisation I have done for me), but lets see if this one go through first ;) let me know if you have any questions.

**Comment by brotzky** [comment]
Thats awesome @Haja-andri :) Super cool to hear and that's a fantastic accomplishment.

Will checkout the PR.

**Comment by alfieqashwa** [comment]
Hi @Haja-andri. I looked at your blog. That's awesome customization. Agree, Novela is really beautiful theme.

**Comment by brotzky** [comment]
This was merged by the way! Download latest to have some fun.

**Comment by Haja-andri** [comment]
@brotzky Cool ! I'll go celebrate ;) . 

@alfieqashwa I checked your blog as well, I return the compliment, you've done some really nice customisation. I'd like to know more about some of them, maybe we can share few tips here and there... 👍 Let me know how to reach-out

Finally a little favour to both of you. I am also starting my twitter journey (created and account this weekend) and doing followers acquisition manually for now. Follow me [here](https://twitter.com/haja_andriam), I will be sharing some cool stuff soon, including my experience using Gatsby with Novela theme :)
