### ISSUE TITLE
support for blog category

### ISSUE THREAD

**Issue by nnnkit** [narative/gatsby-theme-novela#144]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by brotzky** [comment]
This is definitely something that gets brought up and discussed. Ultimately we've decided to keep Novela barebones without categories, tags, and search for the time-being.

If the community wanted to implement and submit a PR that would be awesome. Otherwise, I can't guarantee categories will be added anytime soon.

**Comment by jcayzac** [comment]
Hello! I see @nnnkit added the feature in the [`@feature/categories`](https://github.com/narative/gatsby-theme-novela/tree/%40feature/categories) branch back in September, and thought it worth mentioning it here since no PR was created and the commits don't cross-reference this issue, so that people coming here know it exists.
