### ISSUE TITLE
Stackbit Theme

### ISSUE THREAD

**Issue by slavakurilyak** [narative/gatsby-theme-novela#190]
<img width="727" alt="Screen Shot 2019-10-23 at 9 21 59 PM" src="https://user-images.githubusercontent.com/6625584/67453312-3194f780-f5db-11e9-9fcc-2a8189bcd33d.png">

It's time to create a Stackbit theme for Novela! [Follow the Stackbit documentation](https://docs.stackbit.com/) to get started.

No Stackbit theme? No worries. Here is a sample repo: https://github.com/stackbithq/stackbit-theme-fjord

Stackbit already supports Gatsby (site generator), Contentful (CMS), Github (repository) and Netlify (build + deploy).

**Comment by brotzky** [comment]
Hey, this looks neat. Thanks for the issue! I believe I've tried looking at converting Novela to stackbit and held off on it because of the amount of work.

Would love if someone from their team could convert Novela to work with Stackbit (or anyone else). Otherwise I'm not sure when we'd be able to do it.

**Comment by slavakurilyak** [comment]
@davbree, @mountainbug95 up for the challenge?

**Comment by brotzky** [comment]
Will reopen if anyone wants to jump on it. For now, it seems like we have no takers.

**Comment by slavakurilyak** [comment]
@denar90, @TomasBankauskas can you guys help out? 🤔

<img width="906" alt="Image+2019-12-02+at+12 19 34+AM" src="https://user-images.githubusercontent.com/6625584/69943002-d7206e00-1499-11ea-87ea-45051fca6590.png">
