### ISSUE TITLE
Add Cypress tests for example website

### ISSUE THREAD

**Issue by aleccool213** [narative/gatsby-theme-novela#267]
## Why?

Automated test coverage is a good thing to have for software development projects to help speed along development. Manually testing pull requests can be tiresome.

## Suggestion

My suggestion is to add [Cypress](https://www.cypress.io/) tests which spin up the example site using the code in the current Git branch. These can be basic and do a few important things:

- Make sure slugs to blog posts work
- Make sure SEO header values are set correctly of posts
- Make sure overriding the global theme works
- e.t.c.

To extend this further, Visual Testing with a service like [Percy](https://percy.io/visual-testing) would introduce a lot of automated test coverage. For instance, screenshots can be taken of the home page and multiple blog posts during Cypress tests. These are used as a "base" and when pull requests are made, the service will diff the new site versus the "base".

**Comment by jpvalery** [comment]
Thanks for the suggestion. 

As mentioned in #249, the vision was to have everything done by GH actions and not rely on any third parties. 

Since this is a demo, I'd tend to think that cypress and percy would be of the end-user responsibility. (_I happen to have developed a GH Action available on the GH Marketplace for Percy: https://github.com/jpvalery/yarn-percy-ci/_). 

I'd consider this a WNF for now; Narative can revisit that decision if they think we should add this to this repo.

**Comment by aleccool213** [comment]
> As mentioned in #242 , the vision was to have everything done by GH actions and not rely on any third parties.

This is fine, Cypress is just an npm module, it can be run on GH actions. 

> Since this is a demo, I'd tend to think that cypress and percy would be of the end-user responsibility. 

I dont believe this is the case, if this package releases a new version with a regression, its the package maintainers responsibility to fix, not the end-users. Adding tests such as Cypress will help prevent regressions.

**Comment by jpvalery** [comment]
> > As mentioned in #242 , the vision was to have everything done by GH actions and not rely on any third parties.
> 
> This is fine, Cypress is just an npm module, it can be run on GH actions. Percy on the other hand is a third-party service which I can understand why there is more resistance there, I still think Cypress tests are needed.

I disagree. They both appear as an external third party IMHO. 

> > Since this is a demo, I'd tend to think that cypress and percy would be of the end-user responsibility.
> 
> I dont believe this is the case, if this package releases a new version with a regression, its the package maintainers responsibility to fix, not the end-users. Adding tests such as Cypress will help prevent regressions.

That's why the current workflows build every time to ensure things still work. 
I see your point though; just unsure how this could all work. 

If you feel strongly about this, you can always build it on your end and open a PR once ready to merge (meaning working workflow + documentation + test protocols).
We can re-evaluate then :)

**Comment by aleccool213** [comment]
If you want to see an example, I have basic Cypress tests working for my own blog using this theme.

tests: https://github.com/aleccool213/blog/tree/master/cypress

circleci config: https://github.com/aleccool213/blog/blob/master/circle.yml

scripts: https://github.com/aleccool213/blog/blob/e2ef35c67cfb7f12c9bacce76c892dd75d6e215c/package.json#L67
