### ISSUE TITLE
How to change footer years

### ISSUE THREAD

**Issue by valtteriak** [narative/gatsby-theme-novela#291]
I'm pretty much new to this and don't know how to change the footer from saying © 2019 to this year.  How does this work? Thanks!

**Comment by brotzky** [comment]
What would you like to change it to? Or do you want to remove that completely?

You can Shadow the component and edit what you like.

https://www.gatsbyjs.org/docs/themes/shadowing/
https://www.gatsbyjs.org/blog/2019-04-29-component-shadowing/

**Comment by anselm94** [comment]
The footer's date works by taking the *Year* of the latest published post. Since the default 'content posts' are dated `2019`, it appears that way. See code [here](https://github.com/narative/gatsby-theme-novela/blob/37bb5268ca0480678aeaec96a36708e94687f273/%40narative/gatsby-theme-novela/src/components/Navigation/Navigation.Footer.tsx#L44-L50)
