### ISSUE TITLE
GIF Support for profile picture

### ISSUE THREAD

**Issue by Aldhanekaa** [narative/gatsby-theme-novela#419]
It would be great if this theme supports gif for the profile picture!

because if I added gif type to profile picture, it will throw an error

**Comment by jshmllr** [comment]
Woo — this is because the profile image is being rendered using `SRCSet` in the `<picture>` element.
Srcset attributes don't work with animated gifs, because they're not static elements.

Looks like anyone tackling this would have to allow for true/false statement if profile `img` is set to `.gif`.
Bigger lift than it appears.
