### ISSUE TITLE
Only JavaScript Syntax is getting highlighted

### ISSUE THREAD

**Issue by chakrihacker** [narative/gatsby-theme-novela#65]
**Version of Novela you are using**
0.2.0
**Number of posts you have and which data source**
8 and local
**Describe the bug**
I use bash scripts and dart language, but only javascript code blocks get syntax highlighting
**To Reproduce**
1. Use any language other than javascript
**Expected behavior**
Should highlight code blocks of any language

**Screenshots**
![image](https://user-images.githubusercontent.com/5210019/63094696-b97cd680-bf86-11e9-9eab-91e01b5ee103.png)

**Comment by brotzky** [comment]
Thanks for creating the issue. Sounds like we should switch from prism
https://github.com/narative/gatsby-theme-novela/issues/51

Will bump the priority of that.

**Comment by brotzky** [comment]
Feel free to follow along on the PR: https://github.com/narative/gatsby-theme-novela/pull/66
Right now ran into an external bug that's blocking progress. Hopefully we'll be able to solve it soon and get this feature shipped in Novela.

**Comment by chakrihacker** [comment]
Sure thanks for the quick update

**Comment by AryanJ-NYC** [comment]
@chakrihacker You need to specify the language after the three backticks. Using your example:

```
```java
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Text("Example")
  }
}
``` // this comment needed to force GitHub to render these backticks properly
```

you'll get:
<img width="748" alt="Screen Shot 2019-08-17 at 4 03 59 PM" src="https://user-images.githubusercontent.com/8263430/63216799-e9ec7e00-c108-11e9-9bef-ee4a7847a98a.png">

Hope that helps!

**Comment by brotzky** [comment]
Ah, yes. I assumed he was specifying the language in his post.
Thanks so much for clarifying @AryanJ-NYC :)

**Comment by chakrihacker** [comment]
Hey, I am specifying language with backticks

**Comment by brotzky** [comment]
@chakrihacker could you share the code you're writing? It looks like Aryan was able to get it done.

**Comment by AryanJ-NYC** [comment]
Just confirming that I'd love to take a look and help out where possible.

**Comment by DanielMartinus** [comment]
I have the same issue with Kotlin. This is because dart and kotlin are not specified as default language in `[prism-react-renderer](https://github.com/FormidableLabs/prism-react-renderer)` https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js

Although Java works, I think that's included in Prisms default set of languages? I'm trying to figure out how I can enable Kotlin.

```
```kotlin
override fun onCreateView(
    inflater: LayoutInflater,
    container: ViewGroup?,
    savedInstanceState: Bundle?
): View? {
    return inflater.inflate(R.layout.fragment_new_blog_post, container, false)
}
``` //
```

![image](https://user-images.githubusercontent.com/1636897/77830920-392d6f00-712c-11ea-9952-b65290c325db.png)

Now, I've seen [this Issue](https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js) in prism-react-renderer where someone is including an extra language. I've tried adding kotlin as extra language by shadowing `Code.Prims.tsx` or `Code.Pre.tsx` but both say they can't find the kotlin-prism file.

Do you have any idea or pointers how I can add Kotlin support?

**Comment by DanielMartinus** [comment]
Nevermind! I just got it solved.

I first had to run `yarn add prismjs` and then shadow `Code.Prism.tsx`. In this file you add the lines from the issue here https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js

```javascript
import Prism from "prism-react-renderer/prism";
(typeof global !== "undefined" ? global : window).Prism = Prism;
require("prismjs/components/prism-kotlin");
```

And then it works 🙂

![image](https://user-images.githubusercontent.com/1636897/77831410-629bca00-712f-11ea-9f3f-5f6ebc444033.png)

**Comment by naoufalelh** [comment]
> Nevermind! I just got it working.
> 
> I first had to run `yarn add prismjs` and then shadow `Code.Prism.tsx`. In this file you add the lines from the issue here [FormidableLabs/prism-react-renderer#53](https://github.com/FormidableLabs/prism-react-renderer/issues/53)
> 
> ```js
> import Prism from "prism-react-renderer/prism";
> (typeof global !== "undefined" ? global : window).Prism = Prism;
> require("prismjs/components/prism-kotlin");
> ```
> 
> And then it works 🙂
> 
> ![image](https://user-images.githubusercontent.com/1636897/77831410-629bca00-712f-11ea-9f3f-5f6ebc444033.png)

do we need to add the code inside `@narative/gatsby-theme-novela/components/Code.Prisme.tsx` like this ?

**Comment by naoufalelh** [comment]
I did put the following inside `@narative/gatsby-theme-novela/components/Code/Code.Prisme.tsx`

```tsx
import Prism from "prism-react-renderer/prism";
(typeof global !== "undefined" ? global : window).Prism = Prism;
require("prismjs/components/prism-ruby");
```

I get this error in the page of the post:

```
TypeError: Cannot read property 'getElementsByTagName' of null
```

I get this warnings:
```
warn "export 'default' (imported as 'CodeBlock') was not found in './Code.Prism'
warn "export 'default' (imported as 'Prism') was not found in './Code.Prism'
```
