### ISSUE TITLE
Dark theme blinks on refresh

### ISSUE THREAD

**Issue by slorber** [narative/gatsby-theme-novela#85]
https://novela.narative.co

When you select dark theme and you refresh the page, it starts as light theme and only then dark theme is applied, which is a bit janky.

I've seen some blogs and other gatsby plugins where the dark theme is handled in a way that prevent this blink effect. For example https://overreacted.io

Basically you need to apply the dark theme as soon as possible, even before the js code is loaded: You inline the js directly into the page's static html output to do something like applying a class "dark" to body.

Unfortunately, what I see is that currently dark theme does not seem to be handled using a body class, but rather some kind of provider component. Fixing this issue might involve more important refactorings

**Comment by brotzky** [comment]
Yes! This has been bothering me as well.
Going to tackle this asap. Thanks.

**Comment by brotzky** [comment]
https://github.com/narative/gatsby-theme-novela/pull/120

Fixed in v0.6.1
I've made it so it doesn't set dark mode and flash. It will only go to mark mode (and stay in dark mode) if the user manually selects it. You can override the default color mode with gatsby-theme-ui-plugin and setting the mode to dark.

**Comment by slorber** [comment]
thanks :)
